@startuml

actor Client

Client -> main : main()
main -> main : readValues()
main -> XmlArticleBuilder : new()
main -> ArticleDirector : new(builder)
main -> ArticleDirector : construct(title, authors, text, hash)
ArticleDirector -> XmlArticleBuilder : buildTitle(title)
ArticleDirector -> XmlArticleBuilder : buildAuthors(authors)
ArticleDirector -> XmlArticleBuilder : buildText(text)
ArticleDirector -> XmlArticleBuilder : buildHash(hash)
main -> XmlArticleBuilder : getResult()
main -> XmlArticleBuilder : reset()
main -> main : writeValues(article)

@enduml
